compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  mocha@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
