packageExtensions:
  console-feed@*:
    dependencies:
      "@types/linkifyjs": "*"
  "@mui/base@*":
    dependencies:
      "@mui/types": "*"
      "csstype": "*"
  "@mui/styled-engine@*":
    dependencies:
      "csstype": "*"
